# Generated by Django 3.2 on 2021-05-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20210521_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsvalue',
            name='value',
            field=models.PositiveIntegerField(),
        ),
    ]
